/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PersonalizeRouteImport } from './routes/personalize'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIdRouteImport } from './routes/workout.$id'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizeRoute = PersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/personalize': typeof PersonalizeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/workout/$id': typeof WorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/personalize': typeof PersonalizeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/workout/$id': typeof WorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/onboarding': typeof OnboardingRoute
  '/personalize': typeof PersonalizeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/workout/$id': typeof WorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/building'
    | '/coach'
    | '/dashboard'
    | '/login'
    | '/mood'
    | '/onboarding'
    | '/personalize'
    | '/profile'
    | '/progress'
    | '/results'
    | '/signup'
    | '/workouts'
    | '/api/stt'
    | '/api/tts'
    | '/workout/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/building'
    | '/coach'
    | '/dashboard'
    | '/login'
    | '/mood'
    | '/onboarding'
    | '/personalize'
    | '/profile'
    | '/progress'
    | '/results'
    | '/signup'
    | '/workouts'
    | '/api/stt'
    | '/api/tts'
    | '/workout/$id'
  id:
    | '__root__'
    | '/'
    | '/building'
    | '/coach'
    | '/dashboard'
    | '/login'
    | '/mood'
    | '/onboarding'
    | '/personalize'
    | '/profile'
    | '/progress'
    | '/results'
    | '/signup'
    | '/workouts'
    | '/api/stt'
    | '/api/tts'
    | '/workout/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingRoute: typeof BuildingRoute
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MoodRoute: typeof MoodRoute
  OnboardingRoute: typeof OnboardingRoute
  PersonalizeRoute: typeof PersonalizeRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  WorkoutsRoute: typeof WorkoutsRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  WorkoutIdRoute: typeof WorkoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalize': {
      id: '/personalize'
      path: '/personalize'
      fullPath: '/personalize'
      preLoaderRoute: typeof PersonalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingRoute: BuildingRoute,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MoodRoute: MoodRoute,
  OnboardingRoute: OnboardingRoute,
  PersonalizeRoute: PersonalizeRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  WorkoutsRoute: WorkoutsRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  WorkoutIdRoute: WorkoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
